name: .NET Core

on:
  push:
    branches: [ master, development, testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Install dependencies
      run: dotnet restore

    - name: Setup PostgreSQL (main)
    # You may pin to the exact commit or the version.
    # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 12
        # POSTGRES_DB - name for the default database that is created
        postgresql db: testApplicationDb 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: postgres
        # POSTGRES_PASSWORD - superuser password
        postgresql password: admin

    - name: Setup PostgreSQL (user)
    # You may pin to the exact commit or the version.
    # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 12
        # POSTGRES_DB - name for the default database that is created
        postgresql db: testApplicationDb 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: postgres
        # POSTGRES_PASSWORD - superuser password
        postgresql password: admin

    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
